
POST http://localhost:5000/auth/signup HTTP/1.1
content-type: application/json

{
  "name": "Edward",
  "email": "edy2022@gmail.com",
  "password": "123456"
}

###

POST http://localhost:5000/auth/signin HTTP/1.1
content-type: application/json

{  
  "email": "jack@gmail.com",
  "password": "123456"
}

###

POST http://localhost:5000/auth/refresh HTTP/1.1
content-type: application/json
Authorization: Refresh eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2tAZ21haWwuY29tIiwic3ViIjoiNjViZDNiN2IzYTUxNjA5MTA3MGYzMTA5IiwiaWF0IjoxNzA3MTYxNjc2LCJleHAiOjE3MDc3NjY0NzZ9.KIVnX_xP-EbavJyWhyOoLUUmetA-y2Ex6Gpgs2lGhWk

###

GET http://localhost:5000/user/all HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImphY2tAZ21haWwuY29tIiwic3ViIjoiNjViZDNiN2IzYTUxNjA5MTA3MGYzMTA5IiwiaWF0IjoxNzA3NzYzMDg2LCJleHAiOjE3MDc3NjM5ODZ9.-XjkUl8EvCkMw-0IOKLaEWTIyZnveiShZEVknoU-pwE

###
POST http://localhost:5000/verifyemail/13e4489eb8a970d752707284df53485672c50f4f72c352415cd504cfb8dfab47 HTTP/1.1
content-type: application/json
